name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init, install and add prettier script
        run: |
          npm init --yes
          npm i -D prettier
          // jq '.scripts += {"format": "prettier --write ."}' package.json > tmpfile && mv tmpfile package.json
          jq --argjson prettierScript '{"format": "prettier --write ."}' '.scripts += $prettierScript' package.json --in-place
          cat package.json
      - name: Run prettier
        run: |
          npm run format
          git --no-pager diff --exit-code --color=never
