name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init, install and add prettier script
        run: |
          npm init --yes
          npm i -D prettier
          constToFind='\"test\": \"echo \\\"Error: no test specified\\\" && exit 1\"'
          replacement=',\n\t\"format\": \"prettier --write .\"'
          combineReplacement="${constToFind//\\/\\\\}${replacement//\\/\\\\}"
          sed -i "s/${constToFind}/${combineReplacement}/g" package.json
          cat package.json
      - name: Run prettier
        run: |
          npm run format
          git --no-pager diff --exit-code --color=never
